# Copyright 2022 ALLIAGE.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Render script
  become: yes
  become_user: "{{ dataset_user }}"
  template:
    src: datasets.sh.j2
    dest: /home/{{ dataset_user }}/datasets.sh
    owner: "{{ dataset_user }}"
    group: "{{ dataset_user }}" 
    mode: 0744

- name: Add tdp-gs alias for {{ dataset_user }} user
  become: yes
  become: "{{ dataset_user }}"
  lineinfile:
    path=/home/{{ dataset_user }}/.bashrc
    line="alias tdp-gs=~/datasets.sh"
    owner={{ dataset_user }}
    regexp='^alias tdp-gs=~/datasets.sh'
    state=present
    insertafter=EOF

# - name: Transfer the script
#   become: yes
#   become_user: tdp_user
#   copy: src=./scripts/datasets.sh dest=/home/tdp_user mode=0777
