# Copyright 2022 ALLIAGE.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Delete folders
  become: yes
  become_user: root
  shell: |
      kinit -kt /home/{{ dataset_user }}/{{ dataset_user }}.keytab {{ dataset_user }}@REALM.TDP
      hdfs dfs -rm -r datasets/{{ datasets.name}}
  ignore_errors: yes
  no_log: yes

- name: Create folder
  become: yes
  become_user: "{{ dataset_user }}"
  shell: |
      kinit -kt /home/{{ dataset_user }}/{{ dataset_user }}.keytab {{ dataset_user }}@REALM.TDP
      hdfs dfs -mkdir -p datasets/{{ datasets.name }}

- name: Move to HDFS
  become: yes
  become_user: "{{ dataset_user }}"
  shell: |
      hdfs dfs -put /tmp/{{ datasets.name }}.{{ datasets.extension }} /user/{{ dataset_user }}/datasets/{{ datasets.name }}

- name: Delete files
  become: yes
  become_user: root
  file:
    path: /tmp/{{ datasets.name }}.{{ datasets.extension }}
    state: absent
  ignore_errors: yes

- name: Delete files compiled
  become: yes
  become_user: root
  file:
    path: /tmp/{{ datasets.name }}.{{ datasets.comp_type }}
    state: absent
  ignore_errors: yes
